### ISSUE TITLE
Under mapping spot on Rival Shores 125337 53627 3922

### ISSUE THREAD

**Issue by paratea** [BoBAdministration/QA-Bug-Reports#14]
**Describe the Bug**
Under rmapping on Rival Shores

**To Reproduce**
1. Log into Rival shores on any pawn
2. TeleportAt 125337 53627 3922

**Screenshots & Video**
![image](https://user-images.githubusercontent.com/77513445/130312697-a87d76a8-e655-49a5-9612-ec49b784f18b.png)

**Branch Version**
Live

**Character Information**
N/A

**Additional Information**
Spot is underwater.

**Comment by Predatoria** [comment]
fixed

**Comment by teatimejess** [comment]
Partially fixed, still able to undermap in this area.

1. Log into Rival Shores on any pawn
2. TeleportAt 126495 55828 3712
3. Move forward.
![image](https://user-images.githubusercontent.com/77513445/134560369-eea0d643-551d-4e61-84de-3ea049d84979.png)

**Comment by Dinorunp** [comment]
> Partially fixed, still able to undermap in this area.
> 
> 1. Log into Rival Shores on any pawn
> 2. TeleportAt 126495 55828 3712
> 3. Move forward.
>    ![image](https://user-images.githubusercontent.com/77513445/134560369-eea0d643-551d-4e61-84de-3ea049d84979.png)

as of 2023 this is not fixed still
