### ISSUE TITLE
Spawn point inhibitors do not inhibit spawning

### ISSUE THREAD

**Issue by Undercooked-Mothman** [BoBAdministration/QA-Bug-Reports#640]
**Describe the Bug**
When a player spawns in as a new dino, their spawn point does not take the inhibitors placed into account. However, when they respawn after dying, the inhibitors work properly

**To Reproduce**
1. Log into dedi 11 (or any tester server with map editing enabled)
2. use the foliage editor to place spawn point inhibitors and disable some spawn points (the more the easier it is to see the effect!)
3. spawn in as a new dino using the character select screen

**Expected behavior**
The closed off spawn points do not allow you to spawn at them in any scenario

**Actual behavior**
The closed off spawn points allow you to spawn at them

**Screenshots & Video**
https://youtu.be/mE-jYL3dLvs

**Branch Version**
Tester

**Character Information**
Tested with terrestrial spawns only

**Additional Information**
Rival shores

**Comment by Predatoria** [comment]
I think they should work now.  I'm going to mark this fixed.  I worked on these quite a bit this week and they seem to be working now.

**Comment by Undercooked-Mothman** [comment]
not fixed! Tested on rival shores again and it seems like instead of the inhibitors not working and letting you spawn in any location from the character select screen, the character select screen just forces you to spawn at one or 2 spawn points over and over again, even with inhibitors. video of the retesting: https://youtu.be/RGRfQ69l5C0

**Comment by Undercooked-Mothman** [comment]
tested again, im worried that using the delete all button to get rid of the spawn inhibitors is acting odd. logged onto dedicated testing 11 (which has restarted since the last time i tested this) to see someone had been testing the border walls/inhibitors. they closed every spawn point except the ones in desert. Used the delete all button to get rid of them. Started spawning in, spawned in desert only. after closing all of the spawn inhibitors in desert, i spawned in the same location as in the video above. It seems like using the delete all button (at least, would need to test more to see if using erase changes the outcome) isnt clearing these spawn inhibitors until the server restarts
